# Generated by Django 4.0.4 on 2022-05-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0003_remove_image_image_image_video_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
