# Generated by Django 4.0.4 on 2022-05-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0004_alter_image_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='File',
        ),
    ]
