# Generated by Django 4.0.4 on 2022-05-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0007_image_height_image_width_alter_file_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagelink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
